---
Resources:
  HelloS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket-by-cloudformation
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            Id: myCORSRuleId1
            MaxAge: 3600
      Tags:
        -
          Key: Purpose
          Value: CloudFormation