Resources:
  MySecureInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      ImageId: ami-02f26adf094f51167
      InstanceType: t2.micro
      SecurityGroups:
        - !ImportValue SSHSecurityGroup
