---
Resources:
  HelloEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f26adf094f51167
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref HelloSSHSG
      Tags:
        -
          Key: Name
          Value: Hello-EC2

  HelloEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref HelloEC2

  HelloSSHSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Sg
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22